### ISSUE TITLE
Save a log of pushes

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#113]
**Is your feature request related to a problem? Please describe.**

We're seeing several things we can't explain with tables being in sync, then out of the blue showing red and claiming to miss data from specific users. We don't have hard data yet, but it seems more like problematic pushes rather than a sync bug. It would be really helpful if CommunityDKP maintained a time line of all pushes in, say, the last 7 days 

both pushes the user has sent as well as pushes they have received, and the type (2 week vs full). This, coupled with my prior feature request for a backup/restore mechanism would help us narrow down what's happening and why we seem to be going out of sync at strange times.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Vapok** [comment]
As mentioned in your previous ticket, we are already aware and working on trying to solve the sync indicator issue.  There's actually nothing out of date, and all data is fine, but the indicator light, in a specific, yet to be determined scenario, is showing missing data, when the reality is, that the data is there.  

We're not going to be adding a list of pushes to this version of the addon, however, if you continue to experience issues, we'd request that you open a bug ticket and include copies of yours and your officers LUA files so that we can better understand the data that you're seeing.

Thanks!
