### ISSUE TITLE
Faction Seperation

### ISSUE THREAD

**Issue by Dees0f** [Vapok/CommunityDKP#35]
I have both a horde and alliance character on the same server. They each overwrite each other instead of staying seperated horde and alliance.

**Comment by Vapok** [comment]
@Dees0f  Can you post your CommunityDKP.lua saved variables or a screenshot?  CommunityDKP automatically separates based on realm and faction.  If it looks like it overwrites it because the table is empty, then that's how it works. Your data should be safe.

Here's an example of mine:
![image](https://user-images.githubusercontent.com/1264136/85244588-1fda4d00-b413-11ea-97f7-0597e56c8d9c.png)

**Comment by Vapok** [comment]
I've tested this pretty thoroughly on both Horde and Alliance alts without issue.  Closing this issue. please reopen if you have additional information to provide.
