### ISSUE TITLE
Value typed in bid your window gets changed if another bidder bids higher than the current high bid.

### ISSUE THREAD

**Issue by jvolkenant** [Vapok/CommunityDKP#67]
**Describe the bug**
When an auction is going on, and say the current bid is 5.  In your window, you type 100 ready to bid, but haven't submitted it yet. If someone else bids higher than 5, your bid value is now changed from 100 to that new minimum valid bid amount.  When may bids happen this way, it makes it difficult to bid in this case.

1) Addon Version and Release e.g. 3.0.0-r20
2) What are your DKP Modes? (screenshot preferred)
![image](https://user-images.githubusercontent.com/10521453/85914472-ed559900-b7f2-11ea-8401-e9d1fa5e3c57.png)
![image](https://user-images.githubusercontent.com/10521453/85914479-f7779780-b7f2-11ea-8298-c5a54d26dd0e.png)

**To Reproduce**
1. Start bid
2. enter in large dkp bid in your bid window but don't submit it yet.  wait to snipe at the end of the auction
3. when another player bids higher than the current high bid watch that your entered bid changes.
4. repeat 2 and 3 until you frustratingly loose the auction :)

**Expected behavior**
Your entered value should not be changed.  While I don't know how you would handle the case where your high entered bid is then under the minimum.

**Comment by Vapok** [comment]
After testing and evaluating the issue, This is actually by design because of the setting "Cost Auto Update Value" being set to First Bidder.  The Bid Box is supposed to update with the highest bid.  I get that there's a desire to not have it update for sniping reasons, but that's currently not an option provided.

**Comment by thunk84** [comment]
Not sure if this comment will get attention since the item is already closed, but here goes...

How about only a small change: when updating the bid value in the text field, if there's already a higher value, then don't update. If there's no value, or the value is lower than the current bid, then go ahead and make the update.
