### ISSUE TITLE
Multi bid

### ISSUE THREAD

**Issue by morrisonk6** [Vapok/CommunityDKP#84]
One of the biggest complaints about DKP bidding for my guild is how long it takes to distribute loot. When we used RCLootCouncil for our loot we could do multiple items at once. Would it be possible to do all the loot on the boss like this? I attached an image of how RC looks to the guild when it gets put out to the raid.
![Capture](https://user-images.githubusercontent.com/35673368/86516423-6c982d80-bdee-11ea-95ab-1504ffb533f3.JPG)

**Comment by Vapok** [comment]
Because of the nature of DKP bidding, and that the completion of one bid affects both desire and/or result of the 2nd bid, doing bids concurrently like this is not possible. It works in Loot Council systems because there's no benefit or constraint on what you select.  

For that matter alone, I do not see this being something that is included in Community DKP.
